services:
  web:
    build: .
    volumes:
      - ./kkutu_data:/kkutu
      - ./global.json:/app/Server/lib/sub/global.json
      - ./auth.json:/app/Server/lib/sub/auth.json
    restart: always
    depends_on:
      - db
    ports:
      - 8000:80
      - 8080:8080
      - 8496-8498:8496-8498
  db:
    build:
      context: .
      dockerfile: ./psql.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:8.4.0-alpine
    volumes:
      - ./redis_data:/data
    restart: always
