services:
  game:
    build: .
    depends_on:
      - db
    volumes:
      - ./config/global.json:/app/Server/lib/sub/global.json
      - ./config/auth.json:/app/Server/lib/sub/auth.json
    command: [ "node", "/app/Server/lib/Game/cluster.js", "0", "1" ]
    restart: always
  web:
    build: .
    volumes:
      - ./kkutu_data:/kkutu
      - ./config/global.json:/app/Server/lib/sub/global.json
      - ./config/auth.json:/app/Server/lib/sub/auth.json
    command: [ "node", "/app/Server/lib/Web/cluster.js", "1" ]
    restart: always
    depends_on:
      - db
      - game
    ports:
      - 80:80
  db:
    build:
      context: .
      dockerfile: ./psql.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - ./db_data:/var/lib/postgresql/data
